environment_version: 1
credentials:
- type: aws
  id: Ry9lpWTCZt0oqAM5
  description: AWS cloud access for Allen
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
